### ISSUE TITLE
Выгрузка данных 

### ISSUE THREAD

**Issue by ElizavetaSh** [mikhailmartin/BestHack2022-DataScience#2]
в файлике https://github.com/mikhailmartin/BestHack2022-DataScience/blob/master/baseline.ipynb 
1. pd.read_csv  dtype инты проставлены с маленькой буквы, что упирается в nan
2. При загрузке данных из time_key=2021-11-03.csv возникает ошибка с пустотой в колонке ["start_time_local"]
ValueError: time data   doesn't match format specified

**Comment by mikhailmartin** [comment]
git pull
и попробуй сейчас
